### PR TITLE
Integrate with power profiles daemon

### PR DESCRIPTION
**Pull request by jhaygood86**
Screenshot from 2021-09-10 23 19 52

Adds integration with power profiles daemon. Only runs if the system bus is active.

Allows changing the active profile via the power wingpanel

### CODE REVIEW

**Review by cassidyjames — COMMENTED** [review]
@jhaygood86 don't forget to add any new files with strings to `po/POTFILES` as well.

**Comment by cassidyjames** [comment]
@elementary/ux there's probably some design input needed here as well. This is the naive design I'd expect for the power profile daemon, but one other thought is that we could treat "Power Saver" more like you see on mobile, as its own standalone toggle. All hardware should have "Power Saver" and "Balanced" modes available, while only some hardware will have a "Performance" mode. And "Power Saver" in the daemon can be hooked off of by other apps as well so it would be a good feature to focus on on its own. Then that leaves the question of: what do we do for hardware that has a "Performance" mode as well?

**Comment by cassidyjames** [comment]
Another note is: we're not currently packaging the power profile daemon, but I think it would be beneficial to do so so we can start using it in places like this and across our apps. @jhaygood86 how were you testing this/how would you recommend doing so?

**Comment by SubhadeepJasu** [comment]
I installed power profiles daemon on my system by hacking the make scripts. For the next release of elementary if we target a new Ubuntu version, I think this wont be a problem.

**Comment by jhaygood86** [comment]
I installed power profiles daemon manually. We will need to package it ourselves since it's not in focal. We will need to apply a small patch for it to build on the focal base for it to build since focal's gudev doesn't have a single helper method that is in the current version, however it's trivial to re-implement in a patch.

I think it's worth it to package it for elementary OS 6.x without waiting on Ubuntu, and switch to Ubuntu's version in OS 7 (assuming they package it in 22.04+)

**Comment by danrabbit** [comment]
Seeing how new power profiles daemon is and that it requires a distro patch to build in OS 6, I'm inclined to wait the 7 months when it should theoretically be maintained upstream. Especially since there are questions about how to do this from a design perspective.

**Comment by jhaygood86** [comment]
> Seeing how new power profiles daemon is and that it requires a distro patch to build in OS 6, I'm inclined to wait the 7 months when it should theoretically be maintained upstream. Especially since there are questions about how to do this from a design perspective.

That would only benefit OS 7, right? Ubuntu versions newer than focal don't require a patch, only focal, due to gudev being one version behind. Focal specifically doesn't have this function:

g_udev_device_get_sysfs_attr_as_int_uncached

The distro patch is just to polyfill that in ppd-driver-platform-profile.c using the focal supported APIs: 

`const gchar *
g_udev_device_get_sysfs_attr_uncached (GUdevDevice  *device,
                                       const gchar  *name)
{
  g_autofree char *path = NULL;
  char *contents = NULL;

  g_return_val_if_fail (G_UDEV_IS_DEVICE (device), NULL);
  g_return_val_if_fail (name != NULL, NULL);

  path = g_build_filename (g_udev_device_get_sysfs_path (device), name, NULL);
  if (!g_file_get_contents (path, &contents, NULL, NULL))
    return NULL;

  return contents;
}

gint
g_udev_device_get_sysfs_attr_as_int_uncached (GUdevDevice  *device,
                                              const gchar  *name)
{
  gint result;
  const gchar *s;

  g_return_val_if_fail (G_UDEV_IS_DEVICE (device), 0);
  g_return_val_if_fail (name != NULL, 0);

  result = 0;
  s = g_udev_device_get_sysfs_attr_uncached (device, name);
  if (s == NULL)
    goto out;

  result = strtol (s, NULL, 0);
out:
  return result;
}
`

**Review by danrabbit — CHANGES_REQUESTED** [review]
I can confirm that this branch sets the power profile, but when the profile is changed from System Settings, the whole panel freezes

**Comment by danirabbit** [comment]
Closing since this was fixed in #262

**Pull request closed without merging**
