### PR TITLE
Different icon for ac only

### PR DESCRIPTION
**Pull request by PowerSnail**
Uses [24-symbolic-ac-adapater](https://github.com/elementary/icons/tree/24-symbolic-ac-adapater) for when there is no battery and only an AC adapter.

### CODE REVIEW

**Comment by PowerSnail** [comment]
For #128.

**Comment by jeremypw** [comment]
Seems reasonable to me but needs OK from design team.

**Comment by danrabbit** [comment]
@cassidyjames can you test this please since I don't have a computer without a battery in it

**Review by danrabbit — APPROVED** [review]
I feel like we could probably come up with a better icon here, but this does the job :+1:

**Pull request merged**
