### PR TITLE
PopoverWidget: Move percent switch to top

### LINKED ISSUE #156: "Show Percentage" on desktop PC shows 0%
As you can see in the screenshot, the widget shows "0%" when the "Show Percentage" option is selected:

image

I think it does not looks well. Probably PCs withotu a battery should not have the "Show Percentage" option at all.

I have 3 Bluetooth devices connected at the same time, I am not sure if they are the reason for this bug? I cannot really disconnect them, because then I will lose my mouse and keyboard :) (the 3rd device - AirPods - are not showing up in the battery widget unfortunately)

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/95265858-show-percentage-on-desktop-pc-shows-0?utm_campaign=plugin&utm_content=tracker%2F60466177&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F60466177&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by danrabbit**
Fixes #156 

Related to a discussion about most other indicators having their middle-click action at the top. Also puts the switch closer to batteries. Looks like:

Screenshot from 2020-10-28 11 07 11

Other indicators sometimes have a separator below the switch. Not sure if we should add that here or remove from other places

Screenshot from 2020-10-28 11 21 46

### CODE REVIEW

**Comment by fabiozaramella** [comment]
I like the second one with the separator 👍🏻

**Comment by fabiozaramella** [comment]
Don't forget to mark this ready for review once it has convinced you. 😉👍🏻

**Comment by cassidyjames** [comment]
I am also leaning toward keeping the separator there for some reason. Also fwiw it looks like we have a separator in the Bluetooth and Notifications indicators, but lack one in the Network indicator.

**Comment by Loreno10** [comment]
In my opinion, the change of order is not needed. The thing at the top should be the most important for the user. The "Show percentage" switch is not something important. I think that in many cases it is something that is clicked only once in the whole "lifetime" of the system installation! I'd even argue that it shouldn't be placed in the menu of the Power indicator - again, it's not a setting that you'd be interested to change very often.
The battery levels is the most important information that the panel offers - therefore, it belong at the top I think.

I think that it doesn't make sense to place the switch at the top just because other indicators have some switch at the top. The other indicators have the switches at the top, but these are completely different kind of switches. They turn ON/OFF some devices. In example, if your turn ON wi-fi, you will see the networks below this switch - it totally makes sense.
In the case of "Power", the "Show percentage" switch is just a minor decoration option, which again, people don't change often.

**Comment by kvdz** [comment]
I think we should move this toggle (show percentage) over to the power settings plugin and not even show it here.

**Comment by cassidyjames** [comment]
@danrabbit this is some real nitpicking, but I'm mostly curious: do you know why the menuitem area here is larger than those in the Notifications and Bluetooth indicators?

indicator-switches

**Comment by danrabbit** [comment]
@cassidyjames my guess would be something to do with the wing panel switch widget and wing panel seps. My plan was to fix all those deprecations in a follow up branch

**Review by cassidyjames — APPROVED** [review]
In that case, this looks good to me!

**Pull request merged**
