### PR TITLE
Drop "Apps Using Lots of Power" feature

### LINKED ISSUE #208: Drop BAMF
## Problem

BAMF is no longer maintained and IIRC it doesn't work in Wayland?

## Proposal

Find a way to drop it

## Prior Art

We replaced it in Gala

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/100268041-drop-bamf?utm_campaign=plugin&utm_content=tracker%2F60466177&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F60466177&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #227: Tries to monitor process 0, which does not exist.
### What Happened?

When running wingpanel in a terminal it was noticed that many warnings like 
```
File '/proc/0/cmdline' doesn't exist.
```
were produced.  

This was tracked to a process id of zero was returned by `Bamf.Window` for certain app windows - in particular those related to a flatpak app.

### Steps to Reproduce

1. In a terminal, stop the wingpanel running with `sudo killall io.elementary.wingpanel` x 2
2. Run wingpanel with `io.elementary.wingpanel`
3. Start some flatpak apps
4. Open the power indicator
5. Terminal warnings appear about non-existent process

### Expected Behavior

The process id should be sanity checked.

### OS Version

6.x (Odin)

### Software Version

Compiled from git

### Log Output

_No response_

### Hardware Info

_No response_

### PR DESCRIPTION
**Pull request by lenemter**
Closes #208
Closes #227

This is not Wayland compatible and IMO useless feature. I'm interested is there someone who thinks otherwise and is against removing this feature?

### CODE REVIEW

**Comment by tintou** [comment]
The only thing I liked was to be able to see that one app is the one currently using all my CPU (and thus the power of my laptop) but that's something I'm okay to trade for wayland support

**Comment by danirabbit** [comment]
Yeah it would be nice if we could do this in a Wayland-compatible way because I think it is handy to be able to see why my fans are going crazy and we don't have any other built-in system monitor feature

**Comment by TomiOhl** [comment]
> we don't have any other built-in system monitor feature

I'd advocate for building a simple system monitor instead, that could be even more useful, albeit arguably it would not provide an "at a glance" answer in all cases. Or maybe just ship gnome's one (although it's design language is very different from elementary).
The default keybinding for launching the task manager in windows is Ctrl + Shift + Esc, wondering how many people know about/use this

**Comment by orowith2os** [comment]
I want to say this feature is able to be implemented on Wayland, just in a different way, but I'm not entirely sure on the technical details.

Here in GNOME, we can see which apps are running in the background reliably by asking Flatpak. If a Flatpak is running in the background (without a window), it'll automatically show in the appropriate menu. This relies on the Flatpak sandbox to work, and so is iffy on native packages; I haven't seen them working with this at all.

Maybe something similar could be looked into for power usage? This would then make it a Flatpak-only feature though, but I don't see much pain in that. Native apps are hell to get working with this anyways.

As for an actual system monitor: basing off of what GNOME has isn't a bad idea. It would definitely help, vs making your own from scratch.

**Review by danirabbit — APPROVED** [review]
Let's go ahead and drop this for now so that we can have a working session and we can figure out how to re-implement such a feature during the cycle if it's important

**Pull request merged**
