### PR TITLE
Improve scale brightness changes with scroll events on touchpads

### PR DESCRIPTION
**Pull request by andirsun**
Currently the scale has glitches when the user make fast movements with touchpad. 

This change fix and normalize behavior with mouse or touchpad. 

## Before

https://user-images.githubusercontent.com/22928302/128289284-c06effdd-98c6-4a54-896a-0086715c1838.mp4

## After

https://user-images.githubusercontent.com/22928302/128289067-414edf56-99a8-4a42-a4e7-4224da7da9af.mp4

### CODE REVIEW

**Review by kvdz — DISMISSED** [review]
nice small change!

question, can it go to a 0% and a 100%?

**Comment by andirsun** [comment]
Yes it can.

**Review by jeremypw — COMMENTED** [review]
Makes sense.  

Presumably the same change should be made to the equivalent code when scrolling on the indicator icon.

**Comment by andirsun** [comment]
This code are implemented in #204

**Pull request closed without merging**
