### PR TITLE
Show the device model if available

### PR DESCRIPTION
**Pull request by alainm23**
Fixed: #274

- Displays device `model` if available
- Fixes spacing when `vendor` property is not available

image

### CODE REVIEW

**Comment by alainm23** [comment]
Probably, but I think the generic name of battery is correct.

**Comment by stsdc** [comment]
Shows bluetooth speaker, but doesn't show headphones :/
image
Screenshot from 2024-12-19 17 34 33

**Comment by alainm23** [comment]
That's weird, maybe we could homogenize the names of the indicator as well as in the configurations.

But that would be another issue.

**Comment by stsdc** [comment]
image
Maybe it doesn't provide enough data. Or doesn't really follow the spec? It is common for Bluetooth devices, unfortunately.

**Comment by alainm23** [comment]
You could verify it by using `D-Spy`, and checking `org.freedesktop.UPower`

image

**Comment by alainm23** [comment]
If your device appears in the settings, it should appear in the indicator, there are probably a couple of extra validations.

**Comment by stsdc** [comment]
Screenshot from 2024-12-19 18 01 31

**Review by stsdc — APPROVED** [review]

**Pull request merged**
